### ISSUE TITLE
Running the contributed command: 'vscode-codeowners.show-owners' failed.

### ISSUE THREAD

**Issue by heavybeard** [jasonnutter/vscode-codeowners#2]
Hello, first of all thanks for your VSCode extension!

I'm finding the following error everytime I try to get the owner of the open file:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
	at assertPath (path.js:39:11)
	at Object.normalize (path.js:287:5)
	at trueCasePathSync 
```

Did you notice the same error? Do you want other infos?

**Comment by jasonnutter** [comment]
@heavybeard Apologies for the delay, somehow been missing notifications for this repo. 

I'll see if I can reproduce this, and let you know if I need more information, thanks!

**Comment by notthatnathan** [comment]
I'm seeing something similar on the command run.

![image](https://user-images.githubusercontent.com/967146/118691097-b9061500-b7d6-11eb-98eb-1aa2baa84ee6.png)

There's also nothing in the status bar.

I'm not sure where to find logs, didn't see them under Output > Extensions.

macOS 11.3.1/VS Code 1.56.2

The syntax highlighting works and is brilliant, thanks.
